version: '3.8'

services:
  app:
    image: laravel-todo-app-php:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8005:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: laravel-todo-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
